// The starting bank of puzzles, checked against the rules rather than against
// the engine that found them.
//
// WHY THIS IS NOT CIRCULAR. src/puzzle-bank.js is generated by a search: the
// engine walked eighty of its own games, found the moments one side gave
// something away, and wrote down the move it liked. Re-running that search to
// check the file would only establish that the engine still agrees with
// itself, which is not the claim the app makes to a person solving one.
//
// So the claims that can be checked WITHOUT the search are checked without it.
// A mate in two is a fact about the rules: it either exists or it does not,
// and a full-width walk of every legal move settles it in a few thousand
// positions. Every "mate in N" in the bank is proved here by exhaustion, and
// so is the claim that the stored move is the one that forces it. The
// evaluation-based entries cannot be proved this way and are checked for shape
// only — that is stated rather than papered over.
import { readFileSync } from 'node:fs';

const src = [
  readFileSync(new URL('../src/engine/bundle.js', import.meta.url), 'utf8'),
  readFileSync(new URL('../src/notation.js', import.meta.url), 'utf8'),
  readFileSync(new URL('../src/puzzle-bank.js', import.meta.url), 'utf8'),
].join('\n');
const { Board, toSan, moveToUci, PUZZLE_BANK } =
  new Function('window', src + '; return { Board, toSan, moveToUci, PUZZLE_BANK };')({});

/** The mating move if the side to move forces mate within `n` moves, else 0. */
function mateIn(board, n) {
  if (n <= 0) return 0;
  for (const move of board.generate()) {
    if (!board.make(move)) continue;
    let forced = false;
    const outcome = board.outcome();
    if (outcome === 'checkmate') forced = true;
    else if (outcome === null && n > 1) forced = everyReplyIsMated(board, n - 1);
    board.unmake();
    if (forced) return move;
  }
  return 0;
}

/** True when every legal reply is still mated within `n` — and there is one. */
function everyReplyIsMated(board, n) {
  let any = false;
  for (const move of board.generate()) {
    if (!board.make(move)) continue;
    any = true;
    const mated = mateIn(board, n) !== 0;
    board.unmake();
    if (!mated) return false;
  }
  return any;
}

let pass = 0, fail = 0;
const ok = (name, cond, extra = '') => { if (cond) pass++; else { fail++; console.log('  FAIL', name, extra); } };

ok('the bank is not empty', PUZZLE_BANK.length > 0, `${PUZZLE_BANK.length} entries`);

let mateClaims = 0, deepMates = 0;
for (const p of PUZZLE_BANK) {
  const board = new Board(p.f);
  const move = board.legalMoves().find((m) => moveToUci(m) === p.u);
  ok(`${p.f}: the stored move is legal`, Boolean(move), p.u);
  if (!move) continue;
  ok(`${p.f}: the algebraic matches the move`, toSan(new Board(p.f), move) === p.n,
    `stored ${p.n}, written ${toSan(new Board(p.f), move)}`);
  ok(`${p.f}: the side to move matches the FEN`,
    p.s === (board.fen().split(' ')[1] === 'w' ? 'white' : 'black'));
  ok(`${p.f}: it is a mate or a gain, not neither`, (p.m ?? null) !== null || (p.e ?? null) !== null);

  if (!p.m) continue;
  mateClaims++;
  // Beyond three, exhaustion is too slow to be worth it here; those are left
  // to the generator and counted so the number is visible rather than implied.
  if (p.m > 3) { deepMates++; continue; }

  const after = new Board(p.f);
  after.make(move);
  const outcome = after.outcome();
  const forces = p.m === 1 ? outcome === 'checkmate' : (outcome === null && everyReplyIsMated(after, p.m - 1));
  ok(`${p.f}: ${p.n} really forces mate in ${p.m}`, forces);
  // And it is not a mate in fewer than claimed, which would make the label wrong.
  if (p.m > 1) {
    const sooner = mateIn(new Board(p.f), p.m - 1);
    ok(`${p.f}: it is not mate in ${p.m - 1}`, sooner === 0,
      sooner ? `${toSan(new Board(p.f), sooner)} mates sooner` : '');
  }
}

console.log(`${PUZZLE_BANK.length} positions, ${mateClaims} mate claims (${mateClaims - deepMates} proved by exhaustion, ${deepMates} too deep to prove here), ${pass} checks passed, ${fail} failed`);
if (fail) process.exit(1);
