import sys, re, shutil, os, os, shutil

# The bundle is regenerated on EVERY build. It was a separate step once, and the
# blunder-rate change went into search.js, was verified in node against
# search.js, and never reached the bundle the page actually ships — so every
# band advertised a blunder rate the opponent never applied. An audit caught it.
core = open('src/engine/core.js').read(); search = open('src/engine/search.js').read()
core = re.sub(r'^export ', '', core, flags=re.M); search = re.sub(r'^export ', '', search, flags=re.M)
search = re.sub(r"import \{[\s\S]*?\} from './core\.js';\n", '', search)
open('src/engine/bundle.js', 'w').write(core + "\n\n" + search)

head = open('src/head.html').read()
body = open('src/body.html').read()

# ── the rating fit, from the measurement, or an honest absence ─────────────
import json, os
if os.path.exists('tools/rating-calibration.json'):
    cal = json.load(open('tools/rating-calibration.json'))
    # WHERE THE SCALE STOPS SEPARATING. A band playing the reviewer's own
    # moves scores near zero loss, so from some strength upward every band
    # looks the same to it. The ceiling per depth is the lowest band from
    # which every stronger band's mean loss sits under the reviewer's own
    # noise (15cp, about a sixth of a pawn). Above it the page says
    # "or above" instead of printing a number the data cannot support.
    NOISE = 15
    ceilings = {}
    bands = sorted({r['elo'] for r in cal['rows']})
    for depth in cal['fits']:
        means = {b: sum(r['meanLoss'] for r in cal['rows'] if r['depth'] == int(depth) and r['elo'] == b)
                    / max(1, sum(1 for r in cal['rows'] if r['depth'] == int(depth) and r['elo'] == b)) for b in bands}
        ceilings[depth] = bands[-1]
        for b in bands:
            if all(means[h] <= NOISE for h in bands if h >= b):
                ceilings[depth] = b
                break
    fit = {'measured': cal['measured'], 'games': cal['games'], 'fits': cal['fits'],
           'bands': bands, 'ceilings': ceilings, 'noise': NOISE}
    print('rating ceilings:', ceilings)
    rating_js = '// Generated by build.py from rating-calibration.json (calibrate-rating.mjs).\nconst RATING_FIT = ' + json.dumps(fit) + ';\n'
    print('rating fit:', {d: round(f['r2'], 3) for d, f in cal['fits'].items()})
else:
    rating_js = '// No calibration has been run, so no rating is estimated anywhere.\nconst RATING_FIT = null;\n'
    print('rating fit: NONE (rating-calibration.json missing)')
open('src/rating-fit.js', 'w').write(rating_js)
# THE `export` KEYWORD IS FOR NODE, NOT FOR THE PAGE. Files the tests import as
# modules — the engine, and the solved pawn endings — declare exports so `node
# --test` can reach them; concatenated into one <script> those same lines are a
# syntax error and the whole app is a blank screen. Stripping them here means a
# file can be both without anybody remembering which it is.
# A GENERATED FILE THAT IS ABSENT IS SAID SO, not raised as a stack trace from
# open(). src/puzzle-bank.js is committed rather than built, because generating
# it takes the best part of an hour, and the first thing anybody does with a
# fresh clone that is missing it should be a sentence telling them which
# command writes it.
if not os.path.exists('src/puzzle-bank.js'):
    print('build.py: src/puzzle-bank.js is missing; the clock mode will have no starting bank.')
    print('           Write one with:  cd tools && node make-puzzles.mjs 80')
    open('src/puzzle-bank.js', 'w').write('// Absent at build time. See tools/make-puzzles.mjs.\nconst PUZZLE_BANK = [];\n')

parts = [re.sub(r'^export ', '', open(f).read(), flags=re.M) for f in [
    'src/engine/bundle.js', 'src/engine/bands.js', 'src/openings.js', 'src/notation.js',
    'src/store.js', 'src/pgn.js', 'src/motifs.js', 'src/rating-fit.js', 'src/review.js', 'src/board-view.js',
    'src/pawn-tb.js', 'src/endgames.js', 'src/puzzle-bank.js',
    'src/icons.js', 'src/traps.js', 'src/app-h.js', 'src/app-g.js', 'src/app-a.js', 'src/app-b.js', 'src/app-d.js', 'src/app-e.js', 'src/app-f.js', 'src/app-k.js', 'src/app-i.js', 'src/app-j.js', 'src/app-l.js', 'src/app-c.js',
]]
script = "<script>\n" + "\n\n".join(parts) + "\n</" + "script>\n"

# ── TWO FILES, and they are not interchangeable ────────────────────────────
#
# The ARTIFACT wants a fragment: the publisher wraps it in its own doctype,
# head and body, and supplies the charset and viewport metas. Sending anyone
# that same fragment as a file is what broke it on a phone — opened from
# Android's Files app it has no charset, so Chrome guesses Windows-1252 and
# every arrow in the interface renders as "Â'", and it has no viewport, so the
# page is laid out at 980px and scaled down to unreadable.
#
# So the standalone file gets a real document around it. Nothing else differs.
fragment = sys.argv[1] if len(sys.argv) > 1 else 'dist/hard-lines-chess.html'
open(fragment, 'w').write(head + "\n" + body + "\n" + script)
print('built', fragment, '(fragment, for publishing)')

def document(extra_head=''):
    return ('<!doctype html>\n<html lang="en-GB">\n<head>\n'
            '<meta charset="utf-8">\n'
            '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n'
            + extra_head + head +
            '\n</head>\n<body>\n' + body + "\n" + script + '</body>\n</html>\n')

standalone = fragment.replace('.html', '-app.html')
open(standalone, 'w').write(document())
print('built', standalone, '(standalone, for sending)')

# ── the installable kit ────────────────────────────────────────────────────
#
# A browser will only install an app from a real address it can attach one to,
# so this is the same page plus the two files that make it installable: a
# manifest it can link, and a service worker, which cannot live inside a single
# file because a worker has to be fetched from its own URL on the same origin.
# Everything else is identical, and the app runs exactly the same without them.
pwa_index = document('<link rel="manifest" href="manifest.webmanifest">\n')
open('dist/pwa/index.html', 'w').write(pwa_index)

# THE WORKER IS GENERATED, AND ITS VERSION IS THE PAGE'S HASH. sw.js was a
# hand-written file with VERSION = 'hard-lines-v1', which nothing bumped, so an
# installed app never saw a new build: the browser compares the worker's bytes,
# found them unchanged, and kept serving the cached shell. Stamping the hash of
# the index.html just written means a changed page is a changed worker, every
# time, without anyone remembering to do it. No template, no build — a kit
# with a stale worker is worse than no kit.
import hashlib
if not os.path.exists('pwa/sw.template.js'):
    sys.exit('build.py: pwa/sw.template.js is missing; the service worker cannot be generated, so nothing was built for pwa/')
sw_template = open('pwa/sw.template.js').read()
if '__VERSION__' not in sw_template:
    sys.exit('build.py: pwa/sw.template.js has no __VERSION__ placeholder to stamp')
sw_version = 'hard-lines-' + hashlib.sha256(pwa_index.encode('utf-8')).hexdigest()[:12]
open('dist/pwa/sw.js', 'w').write(sw_template.replace('__VERSION__', sw_version))
shutil.copy('pwa/manifest.webmanifest', 'dist/pwa/manifest.webmanifest')
for _f in os.listdir('pwa'):
    if _f.endswith('.png'): shutil.copy('pwa/' + _f, 'dist/pwa/' + _f)
print('built dist/pwa/index.html + dist/pwa/sw.js (installable kit: + manifest.webmanifest, icons); worker version', sw_version)
