// The web icons, and src/icons.js which embeds them.
//
// The mark: a two-by-two board in the app's default board colours, rounded,
// on a deep blue ground — the same mark the header draws and the Android
// launcher vector carries. `inset` is the ground margin as a fraction: a
// maskable icon needs a wide one, because Android crops the icon to whatever
// shape the launcher uses and only the middle 80% is guaranteed to survive.
const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const page = (size, inset) => {
  const m = Math.round(size * inset);
  const box = size - m * 2;
  const r = Math.round(box * 0.18);
  return `<html><body style="margin:0;background:#1b2a44">
    <div style="position:absolute;left:${m}px;top:${m}px;width:${box}px;height:${box}px;border-radius:${r}px;overflow:hidden;
                display:grid;grid-template-columns:1fr 1fr;grid-template-rows:1fr 1fr">
      <i style="background:#eeeed2"></i><i style="background:#769656"></i>
      <i style="background:#769656"></i><i style="background:#eeeed2"></i>
    </div></body></html>`;
};

(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--no-sandbox'] });
  const out = {};
  for (const [size, inset, name, key] of [
    [192, 0.10, 'icon-192.png', 'ICON_192'], [512, 0.10, 'icon-512.png', 'ICON_512'], [512, 0.22, 'icon-maskable-512.png', 'ICON_MASKABLE'],
  ]) {
    const p = await browser.newPage({ viewport: { width: size, height: size } });
    await p.setContent(page(size, inset));
    const file = path.join(ROOT, 'pwa', name);
    await p.screenshot({ path: file });
    out[key] = 'data:image/png;base64,' + fs.readFileSync(file).toString('base64');
    await p.close();
  }
  await browser.close();
  fs.writeFileSync(path.join(ROOT, 'src/icons.js'),
    `// ── the app's own icon, inline ─────────────────────────────────────────────
//
// Generated by tools/make-icons.cjs from the brand mark and embedded here, so a
// page that is a single file can still declare a real installable icon. A
// manifest pointing at an icon file that does not exist installs nothing.
const ICON_192 = '${out.ICON_192}';
const ICON_512 = '${out.ICON_512}';
const ICON_MASKABLE = '${out.ICON_MASKABLE}';
`);
  console.log('icons written');
})().catch((e) => { console.error(e.message); process.exit(1); });
